# Generated by Django 3.0.2 on 2020-01-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
